version: "3"
services:
 postgres:
   image: postgres
   container_name: local_postgresql
   restart: always
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: password
   ports:
       - 54322:5432
   volumes:
     - ./data/postgresql:/var/lib/postgresql/data
