version: '3'
services:
  consul:
    image: consul:1.15.4
    restart: always
    container_name: consul_server
    network_mode: bridge 
    volumes: 
      - ./consul:/tmp/consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8302:8302
      - 8400:8400
      - 8500:8500
    command: consul agent -data-dir=/tmp/consul -dev -client=0.0.0.0