version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7.42
    container_name: mysql-5.0
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "TZ=Asia/Shanghai"
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 33006:3306