version: '3.3'
services:
  mysql:
    platform: linux/x86_64
    image: 'mysql:8.0.28'
    container_name: mysql-8.0
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 'testdb'
    restart: always
    volumes: 
      - ./data:/var/lib/mysql
      - ./config/my.cnf:/etc/my.cnf
      - ./init:/docker-entrypoint-initdb.d/
    ports: 
      - '3306:3306'
