version: '3' #指定版本
services:    #服务根节点
  redis:     #redis服务/其他服务（web服务/nginx服务等）
      image: redis:7                            #redis镜像，如果镜像容器没有会去自动拉取
      container_name: redis                     #设置容器名称
      restart: always                           #跟随docker的启动而启动
      ports:
        - 6379:6379